### ISSUE TITLE
询问性能是如何测得100w/s

### ISSUE THREAD

**Issue by 0x333333** [wangtuanjie/ip17mon#2]
Hi @wangtuanjie ,

看到您的代码实现收获不少！另外我想请教下，100w/s的性能是如何测试的？有推荐的压力测试的工具吗？

谢谢！
Zhipeng

**Comment by 0x333333** [comment]
Sorry, 我刚刚看到测试代码中已经有些benchmark的测试方法了。

**Comment by wangtuanjie** [comment]
go test -bench=Find
