### ISSUE TITLE
datx 格式的数据库能否支持下

### ISSUE THREAD

**Issue by liukai2012** [wangtuanjie/ip17mon#6]
ipip推出了datx格式的数据库，能否更新下

**Comment by naryn** [comment]
IPIP.net官方支持datx格式的Golang解析代码 https://github.com/ipipdotnet/datx-go

**Comment by septs** [comment]
您可以尝试一下我的这个实现
https://github.com/NiceLabs/geoip-seeker

**Comment by wangtuanjie** [comment]
https://github.com/wangtuanjie/ip17mon/pull/7
